### ISSUE TITLE
Request for customer IP address in paymentFields.

### ISSUE THREAD

**Issue by travism** [continuous-software/node-virtualmerchant#1]
Hi, I am implementing ecommerce using your module and so far it is working great with one exception. 

There is an additional field that convergepay uses in conjunction with their security settings and I'd like to add them to this module.

Would you add the following?

```
ssl_cardholder_ip
```

Seems pretty quick and low risk. If you would make this change it would help us out. If you want a PR instead let me know.

Thanks

**Comment by kytwb** [comment]
Your PR would be more than welcome! 😄   
Let me know if you can do it and I'll review before merging.

**Comment by travism** [comment]
Addressed here:

https://github.com/continuous-software/node-virtualmerchant/pull/3

**Comment by kytwb** [comment]
Available in the latest npm package.

```
$ npm publish
+ virtualmerchant@1.2.1
```
